version: '3.7'

services:
  mocklogin:
    image: lblod/mock-login-service:0.3.1
  frontend:
    restart: "no"
  identifier:
    restart: "no"
    ports:
      - "80:80"
    environment:
      LOG_ALLOWED_GROUPS: "on"
  dispatcher:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - "8890:8890"
  migrations:
    restart: "no"
  file:
    restart: "no"
  resource:
    restart: "no"
