version: '3.7'

services:
  frontend:
    restart: "no"
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - "8890:8890"
  migrations:
    restart: "no"
  file:
    restart: "no"
  resource:
    restart: "no"
