INSERT DATA {
  GRAPH <http://mu.semte.ch/application> {
<http://data.vlaanderen.be/id/concept/VerkiezingsresultaatGevolgCode/4c713f09-1317-4860-bbbd-e8f7dfd78a2f> <http://mu.semte.ch/vocabularies/core/uuid> "4c713f09-1317-4860-bbbd-e8f7dfd78a2f" ;
	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://mu.semte.ch/vocabularies/ext/VerkiezingsresultaatGevolgCode>, <http://www.w3.org/2004/02/skos/core#Concept> ;
	<http://www.w3.org/2004/02/skos/core#inScheme> <http://data.vlaanderen.be/id/conceptscheme/VerkiezingsresultaatGevolgCode> ;
	<http://www.w3.org/2004/02/skos/core#prefLabel> "Opvolger" ;
	<http://www.w3.org/2004/02/skos/core#topConceptOf> <http://data.vlaanderen.be/id/conceptscheme/VerkiezingsresultaatGevolgCode> .

<http://data.vlaanderen.be/id/concept/VerkiezingsresultaatGevolgCode/89498d89-6c68-4273-9609-b9c097727a0f> <http://mu.semte.ch/vocabularies/core/uuid> "89498d89-6c68-4273-9609-b9c097727a0f" ;
	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://mu.semte.ch/vocabularies/ext/VerkiezingsresultaatGevolgCode>, <http://www.w3.org/2004/02/skos/core#Concept> ;
	<http://www.w3.org/2004/02/skos/core#inScheme> <http://data.vlaanderen.be/id/conceptscheme/VerkiezingsresultaatGevolgCode> ;
	<http://www.w3.org/2004/02/skos/core#prefLabel> "Effectief" ;
	<http://www.w3.org/2004/02/skos/core#topConceptOf> <http://data.vlaanderen.be/id/conceptscheme/VerkiezingsresultaatGevolgCode> .

<http://data.vlaanderen.be/id/concept/VerkiezingsresultaatGevolgCode/dc8169a2-0e20-495d-9e01-30ccc83422b8> <http://mu.semte.ch/vocabularies/core/uuid> "dc8169a2-0e20-495d-9e01-30ccc83422b8" ;
	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://mu.semte.ch/vocabularies/ext/VerkiezingsresultaatGevolgCode>, <http://www.w3.org/2004/02/skos/core#Concept> ;
	<http://www.w3.org/2004/02/skos/core#inScheme> <http://data.vlaanderen.be/id/conceptscheme/VerkiezingsresultaatGevolgCode> ;
	<http://www.w3.org/2004/02/skos/core#prefLabel> "Niet verkozen" ;
	<http://www.w3.org/2004/02/skos/core#topConceptOf> <http://data.vlaanderen.be/id/conceptscheme/VerkiezingsresultaatGevolgCode> .

<http://data.vlaanderen.be/id/conceptscheme/VerkiezingsresultaatGevolgCode> <http://mu.semte.ch/vocabularies/core/uuid> "d1c7ad4b94b94989fa73a4b5f67eeedf" ;
	<http://purl.org/dc/terms/modified> "2018-03-21"^^<http://www.w3.org/2001/XMLSchema#date> ;
	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#ConceptScheme> ;
	<http://www.w3.org/2004/02/skos/core#note> "Persoonlijk gevolg van de uitslag voor de kandidaat dat vastlegt of de kandidaat al dan niet kan deelnemen aan het bestuursorgaan." ;
	<http://www.w3.org/2004/02/skos/core#prefLabel> "VerkiezingsresultaatGevolgCode" .

	}
}