(define-resource user-test ()
  :class (s-prefix "ext:UserTest")
  :properties `((:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified")))
  :has-one `((generated-form :via ,(s-prefix "dct:source")
                   :as "form"))
  :resource-base (s-url "http://data.lblod.info/user-tests/")
  :features `(include-uri)
  :on-path "user-tests")